name: .NET Core Desktop CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet Packages
      run: dotnet restore ./HashNode.Tests/HashNode.Tests.csproj

    - name: Build
      run: dotnet build ./HashNode.Tests/HashNode.Tests.csproj --configuration ${{ matrix.configuration }} --no-restore

    - name: Test
      run: dotnet test ./HashNode.Tests/HashNode.Tests.csproj --no-restore --verbosity normal

